import { FlashCardExercise } from "@/types/course";

export const waterFlashCard: FlashCardExercise = {
  id: 1,
  type: "flashCard",
  question: {
    en: 'Which one of these is "water"?',
    ja: "この中で「水」はどれ？",
    my: 'အဲဒီထဲက ဘယ်ဟာက "ရေ" လဲ။',
    th: 'ข้อใดคือ "น้ำ"?',
    cn: "其中哪一项是“水”？",
    es: '¿Cuál de estos es "agua"?',
    fr: "Lequel de ces éléments est « l’eau » ?",
    hi: 'इनमें से कौन सा "पानी" है?',
    ru: "Что из этого является «водой»?",
  },
  words: [
    {
      id: 0,
      content: {
        en: "tea",
        ja: "おちゃ",
        my: "လက်ဖက်ရည်",
        th: "ชา",
        cn: "茶",
        es: "té",
        fr: "thé",
        hi: "चाय",
        ru: "чай",
      },
      image: "https://www.svgrepo.com/show/475139/tea.svg",
    },
    {
      id: 1,
      content: {
        en: "water",
        ja: "みず",
        my: "ရေ",
        th: "น้ำ",
        cn: "水",
        es: "agua",
        fr: "eau",
        hi: "पानी",
        ru: "вода",
      },
      image: "https://www.svgrepo.com/show/218416/water.svg",
    },
    {
      id: 2,
      content: {
        en: "sushi",
        ja: "すし",
        my: "ဆူရှီ",
        th: "ซูชิ",
        cn: "寿司",
        es: "Sushi",
        fr: "Sushi",
        hi: "सुशी",
        ru: "суши",
      },
      image: "https://www.svgrepo.com/show/402766/sushi.svg",
    },
    {
      id: 3,
      content: {
        en: "rice",
        ja: "ごはん",
        my: "ထမင်း",
        th: "ข้าว",
        cn: "米",
        es: "arroz",
        fr: "riz",
        hi: "चावल",
        ru: "рис",
      },
      image: "https://www.svgrepo.com/show/505200/rice.svg",
    },
  ],
  correctWordId: 1,
};
